"""Added all pokemon to DB

Revision ID: 0273ddc07198
Revises: cc29fe074809
Create Date: 2023-08-06 19:02:57.256638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0273ddc07198'
down_revision = 'cc29fe074809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
