"""added full_details method

Revision ID: 17d3ff05d136
Revises: 7ac64d0f2723
Create Date: 2023-08-07 12:48:51.067864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d3ff05d136'
down_revision = '7ac64d0f2723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
