"""added baseHP and type

Revision ID: 7ac64d0f2723
Revises: 25563d9ac32d
Create Date: 2023-08-07 12:29:32.436521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac64d0f2723'
down_revision = '25563d9ac32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemons', sa.Column('baseHP', sa.Integer(), nullable=True))
    op.add_column('pokemons', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemons', 'type')
    op.drop_column('pokemons', 'baseHP')
    # ### end Alembic commands ###
