"""adding cascades?

Revision ID: b057297893bb
Revises: 17d3ff05d136
Create Date: 2023-08-07 19:05:15.935403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b057297893bb'
down_revision = '17d3ff05d136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
