"""Trying to add render_as_batch

Revision ID: d4a77c2258f9
Revises: 25903122990a
Create Date: 2023-08-07 08:32:22.579892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a77c2258f9'
down_revision = '25903122990a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
